services:
  go:
    build:
      context: .
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go.entrypoints=http"
      - "traefik.http.routers.go.rule=PathRegexp(`/zip_code/[0-9\\-]+`)"
      - "traefik.http.services.go.loadbalancer.server.port=8080"

  traefik:
    image: "traefik:v3.4.1"
    container_name: "traefik"
    command:
        # - "--log.level=DEBUG"
        # - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
